server:
  port: 8000

spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        # Auth Service
        - id: auth-service
          uri: lb://SWCAMP-AUTH-SERVICE
          predicates:
            - Path=/auth/**, /auth
          filters:
            - RewritePath=/auth(?<segment>.*), /api/v1/auth${segment}
        
        # User Service
        - id: user-service
          uri: lb://SWCAMP-USER-SERVICE
          predicates:
            - Path=/user/**, /user
          filters:
            - JwtAuthentication
            - RewritePath=/user(?<segment>.*), /api/v1/users${segment}
        
        # Schedule Service
        - id: schedule-service
          uri: lb://SWCAMP-SCHEDULE-SERVICE
          predicates:
            - Path=/schedule/**, /schedule, /subjects/**, /subjects
          filters:
            - JwtAuthentication
            - RewritePath=/(?<segment>.*), /api/v1/${segment}
        
        # Enrollment Service
        - id: enrollment-service
          uri: lb://SWCAMP-ENROLLMENT-SERVICE
          predicates:
            - Path=/enrollments/**, /enrollments
          filters:
            - JwtAuthentication
            - RewritePath=/enrollments(?<segment>.*), /api/v1/enrollments${segment}
        
        # Course Service
        - id: course-service
          uri: lb://SWCAMP-COURSE-SERVICE
          predicates:
            - Path=/courses/**, /courses
          filters:
            - JwtAuthentication
            - RewritePath=/courses(?<segment>.*), /api/v1/courses${segment}

        # Attendance Service
        - id: attendance-service
          uri: lb://SWCAMP-ATTENDANCE-SERVICE
          predicates:
            - Path=/attendance/**, /attendance
          filters:
            - JwtAuthentication
            - RewritePath=/attendance(?<segment>.*), /api/v1/attendance${segment}
        
        # Reservation Service
        - id: reservation-service
          uri: lb://SWCAMP-RESERVATION-SERVICE
          predicates:
            - Path=/reservation/**, /reservation
          filters:
            - JwtAuthentication
            - RewritePath=/reservation(?<segment>.*), /api/v1/reservation${segment}
